ruleset:
  comment_and_close_issue:
    name: "Comment, label & close issues"
    events: [ issues ]
    label: invalid
    when:
      - action = "opened"
    close: true
    comment: >
      Hi @{{ user.login }}
      
      We have moved to the [forum](http://forum.freecodecamp.com/c/wiki). We no longer accept opening new issues.

      Happy Coding!
  comment_and_close_pull_request:
    name: "Comment, label & close pull requests"
    events: [ pull_request ]
    label: invalid
    when:
      - action = "opened"
    close: true
    comment: >
      Hi @{{ user.login }}
      
      We have moved to the [forum](http://forum.freecodecamp.com/c/wiki). Please make your changes there.

      Happy Coding!
       
      Happy Coding!
      
